### ISSUE TITLE
Figure out weighted aggregation

### ISSUE THREAD

**Issue by JosiahParry** [nptscot/rnetmatch#22] opened 2024-02-01 16:44 UTC
Here is a reprex: 

```r
library(sf)
library(dplyr)

x_raw <- read_sf("data-raw/geojson/intersection_example_simple.geojson") |> 
  sf::st_transform(27700)
y_raw <- read_sf("data-raw/geojson/intersection_example_complex.geojson") |> 
  sf::st_transform(27700)

# perform match
mtx <- rnetmatch::rnet_match(x_raw, y_raw, 50, 15) 

# aggregate weighting Yj by shared_len / yj_len
# i think this is the correct approach b/c we determine the amount of 
# shared length on x and we want to add attributes from y.
# we weight attr from y based the shared length. The weight should be
# yj_val * (shared_len / yj_len)
mtx |> 
  as_tibble() |> 
  left_join(
    y_raw |> 
      st_drop_geometry() |> 
      mutate(, j = row_number()) |> 
      select(j, commute_quietest_bicycle_go_dutch)
  ) |> 
  arrange(i, j) |> 
  mutate(
    x_len = st_length(x_raw)[i],
    y_len = st_length(y_raw)[j]
  ) |> 
  mutate(wt = shared_len / y_len) |> 
  print() |> # print the intermediate obj
  group_by(i) |> 
  summarise(
    weighted_shared = sum(wt * commute_quietest_bicycle_go_dutch, na.rm = TRUE)
  )
#> Joining with `by = join_by(j)`
#> # A tibble: 73 × 7
#> i     j shared_len commute_quietest_bicycle_go_dutch x_len   y_len     wt
#> <int> <int>      <dbl>                             <dbl>   [m]     [m]  [1/m]
#> 1     1     8      78.3                                 90  78.3   78.3  1.00  
#> 2     1    10       0                                   97  78.3    7.82 0     
#> 3     1    30      36.0                               2004  78.3  551.   0.0652
#> 4     2     1       7.50                                 8  92.3   82.0  0.0914
#> 5     2     2      43.4                                  8  92.3   51.0  0.850 
#> 6     2     9      92.3                                 90  92.3   92.3  1.00  
#> 7     2    21      35.8                                  0  92.3  133.   0.268 
#> 8     2    30      15.2                               2004  92.3  551.   0.0275
#> 9     2    31       0                                 2094  92.3 1237.   0     
#> 10     3     1      83.7                                  8 551.    82.0  1.02  
#> # ℹ 63 more rows
#> # ℹ Use `print(n = ...)` to see more rows
#> # A tibble: 11 × 2
#> i weighted_shared
#> <int>           [1/m]
#> 1     1           221. 
#> 2     2           153. 
#> 3     3          2201. 
#> 4     4          2095. 
#> 5     5          1032. 
#> 6     6           686. 
#> 7     7           200. 
#> 8     8           237. 
#> 9     9           138. 
#> 10    10            59.1
#> 11    11             0  
```

**Comment by Robinlovelace** [comment] 2024-02-01 17:03
Well stated and we need to work this one out..

**Comment by Robinlovelace** [comment] 2024-02-01 17:25
Check on the `stplanr::rnet_merge()` implementation:

```
> sum(rnet_merged$commute_fastest_bicycle_go_dutch * sf::st_length(rnet_merged$geometry))
1758359 [m]
> # And for the complex network:
> sum(rnet_yp$commute_fastest_bicycle_go_dutch * sf::st_length(rnet_yp$geometry))
1758359 [m]
```

That's because we hardcode it to be so... That doesn't answer the immediate question but may be relevant here, if the total distance travelled in fixed it becomes more about how we distribute the values. Although for the test datasets there should be an unambiguous right answer.

**Comment by Robinlovelace** [comment] 2024-02-01 17:26
Reprex: code just above this bit:

https://github.com/nptscot/rnetmatch/blob/85b123ea3139435556870b91f5c53634024af378/r/demo.qmd#L70

**Comment by Robinlovelace** [comment] 2024-02-01 17:26
Will take a look later this evening..

**Comment by JosiahParry** [comment] 2024-02-02 01:22
I'm not sure what this tells us, but compared to stplanr.

This approximate network match algo is calculating the "shared overlap" between two line segments  with regard to rnet_xp in this case. So we can use the value of shared length to give us the value of y scaled by the length  of overlap. Whereas stplanr is giving us an average of all values 
```r
library(sf)
library(dplyr)

rnet_xp <- read_sf("data-raw/geojson/intersection_example_simple.geojson") |> 
  sf::st_transform(27700)
rnet_yp <- read_sf("data-raw/geojson/intersection_example_complex.geojson") |> 
  sf::st_transform(27700)

dist = 10
angle = 5

# determine aggrgate functions based on var name
cnames <- colnames(st_drop_geometry(rnet_yp))
funs <- ifelse(
   cnames %in% c("Gradient", "Quietness"),
  list(mean), list(sum)
) |> setNames(cnames)

rnet_merged = stplanr::rnet_merge(
  rnet_xp,
  rnet_yp,
  dist = dist,
  funs = funs,
  max_angle_diff = angle,
  segment_length = 10
)  |> 
  mutate(i = row_number())

mtx <- rnet_match(rnet_xp, rnet_yp, 10, 5)

library(dplyr)
# aggregate weighting Yj by shared_len / yj_len
# i think this is the correct approach b/c we determine the amount of 
# shared length on x and we want to add attributes from y.
# we weight attr from y based the shared length. The weight should be
# yj_val * (shared_len / yj_len)
mtx |> 
  as_tibble() |> 
  left_join(
    rnet_yp |> 
      st_drop_geometry() |> 
      mutate(j = row_number()) |> 
      select(j, commute_quietest_bicycle_go_dutch)
  ) |> 
  arrange(i, j) |> 
  mutate(
    x_len = st_length(rnet_xp)[i],
    y_len = st_length(rnet_yp)[j]
  ) |> 
  mutate(wt = shared_len / y_len) |> 
  group_by(i) |> 
  summarise(
    weighted_shared = sum(wt * commute_quietest_bicycle_go_dutch, na.rm = TRUE),
    total = sum(commute_quietest_bicycle_go_dutch),
    mean = mean(commute_quietest_bicycle_go_dutch)
  ) |> 
  left_join(
    st_drop_geometry(rnet_merged[c("i", "commute_quietest_bicycle_go_dutch")]),
    by = "i"
  )
 #> # A tibble: 10 × 5
#> i weighted_shared total   mean commute_quietest_bicycle_go_dutch
#> <int>           [1/m] <dbl>  <dbl>                             <dbl>
#> 1     1           90.0    187   93.5                             NA   
#> 2     2           90.0     90   90                               23.0 
#> 3     3         2004.    2004 2004                             2562.  
#> 4     4         2094.    2094 2094                             1900.  
#> 5     5          344.     396   56.6                             32.2 
#> 6     6           29.8   2028  406.                               1.53
#> 7     7           84.7    386   96.5                             23.5 
#> 8     8          129.     184   61.3                              2.92
#> 9     9           55.3    265  132.                             154.  
#> 10    10            4.91    13   13                                6.01
```

**Comment by JosiahParry** [comment] 2024-02-03 20:29
For categorical variables we can report proportion per-class in a wide format.
For numeric variables we can provide a weighted sum. Additional options should be handled by the user. Vignette describing how to do so can be provided.

**Comment by Robinlovelace** [comment] 2024-02-04 00:29
#26 seems to go a long way towards that, and I think gives people flexibility to aggregate as they want.

**Comment by Robinlovelace** [comment] 2024-02-04 01:29
One question I've got on this, using the example from #27, how is the value of the middle line 4 not 5?

It's surrounded by 2 features with roughly equal length that have values of 2 and 4 so in my head the weighted sum should be ~5.

Reprex:

```
x <- read_sf("data-raw/geojson/princes_street_minimal_x_1.geojson") |>
  sf::st_transform(27700)
x = x[3, ]
y <- read_sf("data-raw/geojson/princes_street_minimal.geojson") |>
  sf::st_transform(27700)
y = y[2:3, ]
matches <- rnetmatch::rnet_match(x, y, dist_tolerance = 10, angle_tolerance = 5)
y_aggregated <- rnet_aggregate(x, y, matches, value)
y_joined <- cbind(x, y_aggregated)
plot(y["value"], lwd = 5)
plot(y_joined["value"], lwd = 5)
y_y_joined <- dplyr::bind_rows(y["value"], y_joined["value"])
plot(y_y_joined, lwd = 5)
```

Result:

![image](https://github.com/nptscot/rnetmatch/assets/1825120/74448971-fe9f-420f-90af-91b86f07da6f)

or `y$value`:

```
y_joined$value
[1] 4.010027
```

More tomorrow!

**Comment by JosiahParry** [comment] 2024-02-04 02:30
I think its this part of the code. The shared length is the entirety of x but _less_ than the entirety of `y`. So we scale the value of `y` by the proportion of y shared with x. If we multiply the wt by value it becomes a bit clearer. 
```
dplyr::bind_cols(matches, ij) |>
+     dplyr::mutate(
+       wt = shared_len / y_len[j],
+       wt * value
+     )
  i j shared_len value              wt     wt * value
1 1 2   77.58872     3 0.7891202 [1/m] 2.367361 [1/m]
2 1 1   77.58872     2 0.8213332 [1/m] 1.642666 [1/m]
```

**Comment by JosiahParry** [comment] 2024-02-04 02:31
Essentially, we're removing from the value proportional to the amount of line _not shared_ with x

**Comment by Robinlovelace** [comment] 2024-02-04 08:21
This suggests to me we're calculating the weights wrong. It they should be based on the proportion of the length of `y` that overlaps with `x`. I'm fairly confident of that. Reasoning:

Imagine that our model for Princes Street results in the finding that 5 trips per day happen along it, one on the north and one on the south side of the road. The purpose of the join is to find out how those trips can be represented when the network only has a single centreline.

**Comment by Robinlovelace** [comment] 2024-02-04 08:21
Will try to update it to be based on dividing by the length of y not x..

**Comment by Robinlovelace** [comment] 2024-02-04 08:38
Looking at the Rust code :confused: 

Is this the bit where the shared overlap is calculated?

https://github.com/nptscot/rnetmatch/blob/fae43671b8e7445e7d156e1832c8205fcb71103f/rust/src/overlap.rs#L116-L118

If I think it should be the other way around, so we calculate the proportion of each y that overlaps with each x, ~100% for both ys in the example above which should lead to something like

```
x_value = (y_1_shared_length * y_1_value + y_2_shared_length * y_2_value) / length_x
```

Given that `x` in this case is 71.7 m that would be something like

``` r
(71.7 * 3 + 71.7 * 2)/71.7
#> [1] 5
```

<sup>Created on 2024-02-04 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

So I think we actually need to be calculating as the proportion of x in y not vice versa, for this motivating use case of re-assigning known flows.

**Comment by JosiahParry** [comment] 2024-02-04 13:48
What you're describing would be weighting by `shared_length / length_x` which is what I had initially done and i think we both agree is wrong. Why weight a value in `y` based on the length of `x`? It doesn't make sense.

I believe the code here is correct 

In your example, the length of x is `77.58` the length of the 2 y values are `94.4` and `98.3` respectively. They are _longer_ than the `x` that they are matched to. By weighting proportional to the overlap (77.5/994) and (77.58/98.3) we get 0.82 and 0.789. To get a rough estimate of the values in y _scaled by the overlap of x_ we multiply the value by the proportion of overlap. We'll only ever get less or exactly the same value of y because the proportion cannot be greater than 1. Multiplying 0.82 * 2 and `0.789 * 3` gives us 1.64 and 2.36.

Changing which line we calculate the overlap from in the Rust code will only change the length of the segment depending on the different in slope. If there is no difference in slope then values will be identical.

``` r
library(sf)
#> Warning: package 'sf' was built under R version 4.3.1
#> Linking to GEOS 3.11.0, GDAL 3.5.3, PROJ 9.1.0; sf_use_s2() is TRUE
library(rnetmatch)
x <- read_sf("data-raw/geojson/princes_street_minimal_x_1.geojson") |>
  sf::st_transform(27700)
x = x[3, ]
y <- read_sf("data-raw/geojson/princes_street_minimal.geojson") |>
  sf::st_transform(27700)

(x_len <- st_length(x))
#> 77.58872 [m]

matches <- rnet_match(x, y, 10, 5)

(y_len <- st_length(y[2:3,]))
#> Units: [m]
#> [1] 94.46680 98.32306

wts <- as.double((x_len / y_len))
wts
#> [1] 0.8213332 0.7891202

# pull values
y_vals <- y$value[2:3]

# multiply to get shared length weighted
(y_weighted <- y_vals * wts)
#> [1] 1.642666 2.367361

# then we sum 
sum(y_weighted)
#> [1] 4.010027
```

**Comment by Robinlovelace** [comment] 2024-02-04 20:24
I think it's the % of x covered by y that we're interested in. The main thing: we need to capture the fact that 5 trips per day happen on that corridor for our transport planning and currently that doesn't seem to be happening, although maybe the numbers will work out on a wider network. Another great example we can use is the Forth Bridge Road where we have 2 parallel sets of linestrings that should be merged into 1 that represents the potential levels of cycle traffic:

![image](https://github.com/nptscot/rnetmatch/assets/1825120/9a0e38d4-28c0-4984-8e36-026bd7efff8e)

Source: https://www.npt.scot/#14.16/55.98601/-3.38688

Maybe that would be a good example? The Edinburgh one is imperfect because the central lines don't add up. Would be interested to see what happens if the length of x is even smaller... More tests needed.

**Comment by JosiahParry** [comment] 2024-02-05 02:14
You can get this by weighting `shared_len / x_len`. And I think they are two distinct and separate problems.
First, here is how you might repro what you're describing. This gives us 

```r
library(sf)
library(rnetmatch)
x <- read_sf("data-raw/geojson/princes_street_minimal_x_1.geojson") |>
  sf::st_transform(27700)
y <- read_sf("data-raw/geojson/princes_street_minimal.geojson") |>
  sf::st_transform(27700)

x_len <- st_length(x)
y_len = sf::st_length(y)
matches <- rnet_match(x, y, 10, 5)

# subset vars by j to get ij pairs
ij <- y$value[matches$j]

dplyr::bind_cols(matches, value = ij) |>
  dplyr::mutate(
    # create weight by amount of x covered by y
    wt = as.numeric(shared_len / x_len[i]),
    weighted = value * wt
  ) |>
  dplyr::group_by(i) |>
  # sum the totals
  dplyr::summarise(value = sum(weighted))
#>  # A tibble: 3 × 2
#>      i value
#>   <int> <dbl>
#> 1     1  3.90
#> 2     2  1.74
#> 3     3  5    
```

I do think this is a bit of a risky attribution though. For example we can run into a situation where we're attributing a value from y to x where y is a kilometer longer than x. So thats 1000 meters of "value" as it were, that is being attributed to x for segment that is not shared with x. Here's an example where I try to illustrate the risk of this. If we use the weight of `shared_len / x_len` we'll be giving each of these the entire value of y to x. The below visualizes all of the matches where y is 300+ meters longer than x. 

Because of this, I think the most accurate thing to do is to scale by the length of y `y_val * (shared_len / length_y)`

``` r
library(sf)
library(dplyr)
library(rnetmatch)

open_roads = sf::read_sf("https://github.com/nptscot/networkmerge/releases/download/v0.1/os_3km.geojson") |> 
  st_make_valid()

case_study_area = open_roads |>
  sf::st_union() |>
  sf::st_convex_hull() |>
  sf::st_transform("EPSG:4326")

osm_roads = osmextract::oe_get_network(
  "Edinburgh",
  mode = "driving",
  boundary = case_study_area,
  boundary_type = "clip"
)
x <- open_roads |> 
  dplyr::transmute(n = seq(nrow(open_roads))) |> 
  sf::st_transform("EPSG:27700") |> 
  sf::st_cast("LINESTRING")

y <-  osm_roads |> 
  sf::st_cast("LINESTRING") |> 
  sf::st_zm() |> 
  sf::st_transform("EPSG:27700")
#> Warning in st_cast.sf(osm_roads, "LINESTRING"): repeating attributes for all
#> sub-geometries for which they may not be constant

matches <- rnet_match(x, y, 5, 5)


x_len <- st_length(x)
y_len <- st_length(y)

yj_longer_than_xi <- matches |> 
  as_tibble() |> 
  mutate(
    xi_len = x_len[i],
    yj_len = y_len[j],
    wt = as.numeric(shared_len / xi_len)
  ) |> 
  filter(wt == 1, as.numeric(yj_len) > shared_len) |> 
  mutate(
    meters_longer = yj_len - xi_len
  ) |> 
  arrange(-meters_longer) |> 
  filter(as.numeric(meters_longer) > 200)

# we'll be attributing values from line segments that are sometimes a whole
# kilometer longer than its matched element.
head(yj_longer_than_xi)
#> # A tibble: 6 × 7
#>       i     j shared_len xi_len yj_len    wt meters_longer
#>   <int> <int>      <dbl>    [m]    [m] <dbl>           [m]
#> 1  3476   574       55.3   55.3  1060.     1         1005.
#> 2  1184  3416       46.2   46.2  1040.     1          994.
#> 3   602  3416       80.7   80.7  1040.     1          959.
#> 4   598  3416       90.8   90.8  1040.     1          949.
#> 5   574  3416       96.0   96.0  1040.     1          944.
#> 6  3659   574      175.   175.   1060.     1          885.

xx <- st_geometry(x)[unique(yj_longer_than_xi$i)]
yy <- st_geometry(y)[unique(yj_longer_than_xi$j)]

xy <- bind_rows(
  st_sf(set = "A", alpha = 0.75, geometry = xx),
  st_sf(set = "B", alpha = 0.5, geometry = yy),
)

ggplot(xy, aes(color = set)) +
  geom_sf(lwd = 1.5, alpha = xy$alpha) +
  theme_void() +
  scale_color_brewer(type = "qual", palette = 2) +
  labs(title = "Matches where B is 300+ meters longer than A")
```

![](https://i.imgur.com/DceVqQy.png)

<sup>Created on 2024-02-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Robinlovelace** [comment] 2024-02-05 15:42
Reproducible example that shows how currently the values associated with x depend on the target geometry.

Both `x` and `x_segmented` represent the same bit of road but the values associated with them are very different:

``` r
# setup input dataset:
x = sf::read_sf("data-raw/geojson/princes_street_minimal_x_1.geojson") |>
  sf::st_transform(27700)
y = sf::read_sf("data-raw/geojson/princes_street_minimal.geojson") |>
  sf::st_transform(27700)

x = x[3, ]
y = y[2:3, ]
matches <- rnetmatch::rnet_match(x, y, dist_tolerance = 10, angle_tolerance = 5)
y_aggregated <- rnet_aggregate(x, y, matches, value)
y_joined <- cbind(x, y_aggregated)
y_joined
```

    Simple feature collection with 1 feature and 3 fields
    Geometry type: LINESTRING
    Dimension:     XY
    Bounding box:  xmin: 325720.5 ymin: 673966.8 xmax: 325794.8 ymax: 673989.3
    Projected CRS: OSGB36 / British National Grid
      id i    value                       geometry
    1  3 1 4.010027 LINESTRING (325720.5 673966...

``` r
x_segmented = stplanr::line_segment(x, segment_length = 10)
matches <- rnetmatch::rnet_match(x_segmented, y, dist_tolerance = 10, angle_tolerance = 5)
y_joined_segmented <- rnet_aggregate(x_segmented, y, matches, value)
y_joined_segmented
```

    # A tibble: 8 × 2
          i value
      <int> <dbl>
    1     1 0.501
    2     2 0.501
    3     3 0.501
    4     4 0.501
    5     5 0.501
    6     6 0.501
    7     7 0.501
    8     8 0.501

``` r
sum(y_joined_segmented$value)
```

    [1] 4.010027

``` r
funs = list(value = sum)
# With stplanr:
rnet_merged = stplanr::rnet_merge(x, y, dist = 10, funs = funs, max_angle_diff = 5, sum_flows = FALSE)
```

    Warning: st_centroid assumes attributes are constant over geometries

    Joining with `by = join_by(id)`

``` r
rnet_merged_segmented = stplanr::rnet_merge(x_segmented, y, dist = 10, funs = funs, max_angle_diff = 5, sum_flows = FALSE)
```

    Warning: st_centroid assumes attributes are constant over geometries

    Joining with `by = join_by(id)`

``` r
rnet_merged$value
```

    [1] 5

``` r
rnet_merged_segmented$value
```

    [1] 5 5 5 5 5 5 5 5

That's from #29, don't need to merge it..

**Comment by Robinlovelace** [comment] 2024-02-05 15:53
A key distinction is whether the attributes are intensive or extensive: https://r-spatial.org/book/05-Attributes.html#sec-extensiveintensive

For extensive attributes we would divide the values by the area or the length of the road, e.g. number of estimated cycle line markings that can be assumed to increase with distance.

In this case we're talking about flow along the linestring, so if it's 5 at the start for the first 1 meter it will be 5 at the end. Currently, however, the implementation treats it as an extensive attribute, so if you have a 5 m length of road with a value of 5 split into 5 5 m sections it will re-set the value to 1 for each sub-linestring.

Could we have an argument like `intensive = TRUE` to differentiate between intensive and extensive variables? 

I don't know of any extensive linestring attributes that you'd want to calculate by dividing by the distance but imagine they exist and that they would be useful for some use cases.

**Comment by Robinlovelace** [comment] 2024-02-05 16:01
From your code above @JosiahParry, this does what we want by the looks:

```
dplyr::bind_cols(matches, value = ij) |>
  dplyr::mutate(
    # create weight by amount of x covered by y
    wt = as.numeric(shared_len / x_len[i]),
    weighted = value * wt
  ) |>
  dplyr::group_by(i) |>
  # sum the totals
  dplyr::summarise(value = sum(weighted))
#>  # A tibble: 3 × 2
#>      i value
#>   <int> <dbl>
#> 1     1  3.90
#> 2     2  1.74
#> 3     3  5  
```

**Comment by JosiahParry** [comment] 2024-02-06 21:19
@Robinlovelace, in your case, does it make more sense to ignore weighting entirely?

**Comment by Robinlovelace** [comment] 2024-02-06 22:05
> @Robinlovelace, in your case, does it make more sense to ignore weighting entirely?

Not sure, need to do more tests... In my court. More repexes from me below soon...

**Comment by Robinlovelace** [comment] 2024-02-06 22:13
When features of x are longer than y I think we need weighting to distribute the values. See example below.

![image](https://github.com/nptscot/rnetmatch/assets/1825120/133104db-dcc5-421f-b604-c8b1b6f71f2c)


Source (feel free to edit): https://excalidraw.com/#room=74e6f251c4cc4756aaec,t7_CtachJHbo-L7rCIS3xQ

**Closed** 2024-02-25 19:23 UTC
